### ISSUE TITLE
Minor comments on the README

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-grasp-demo#1]
@giuliavezzani well done with the README!

I've got a couple of suggestions though, _which you might be already considering_:
- It'd be quite important to expose more information on the **visual-servoing**; perhaps @claudiofantacci can help on this.
- Linking the **video** could make the documentation even more appealing 😄

**Comment by giuliavezzani** [comment]
Ok, I'll improve it asap :smile:

**Comment by giuliavezzani** [comment]
A comment on what @pattacini suggested. I have already provided a more detail description of the `visual-servoing` in the README.md of the [`superquadric-grasp` module](https://github.com/robotology/superquadric-grasp/tree/master/tutorial#fine-pose-reaching-with-visual-servoing). 
Should I link to this section in the `icub-grasp-demo` or should I "copy&paste" it also in the `icub-grasp-demo` README.md?
 While writing the README.md, I followed this standard: in the `icub-grasp-demo` I only provide high-level information. The information strictly related to one module is in the relative repository.

**Comment by pattacini** [comment]
Ok then, no need to expand on the tools behind any further 👍 

Just make sure that you clearly state to refer to the documentation of the single modules somewhere and, yes, put a slight emphasis here in on the fact that we're using visual-servoing too (a couple of lines are enough). I had a quick glance at the README yesterday and didn't catch it.

Thanks!

**Comment by giuliavezzani** [comment]
Yes, I definitively have to stress the point that visual servoing is used in the demo and where is the relative information. :+1:
