### ISSUE TITLE
Provide supporting slides

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-grasp-demo#3]
Put in `/misc` some slides in **PDF** describing:
- superquadrics
- modeling optimization
- grasping optimization
- visual-servoing

They're very useful to support the demo.

**Comment by giuliavezzani** [comment]
A few slides describing the modeling and grasping pipeline are in the [`misc` folder](https://github.com/robotology/icub-grasp-demo/blob/master/misc/icub-grasp-slide.pdf).

**Comment by pattacini** [comment]
Thanks @giuliavezzani 👍 
I'd only update the index accounting for the hand selection since values displayed on the screen and the formula are not in agreement.

@claudiofantacci when you'll have some spare time, could you extend these slides including your part?

**Comment by giuliavezzani** [comment]
@pattacini , you are right! I'll do it immediately.

**Comment by claudiofantacci** [comment]
> @claudiofantacci when you'll have some spare time, could you extend these slides including your part?

I'll work on it starting from next week.

**Comment by giuliavezzani** [comment]
Slides describing the entire demo (`modeling`+`grasping`+`visual-servoing`) have been added.
