### ISSUE TITLE
New trajectory for cleaning the table

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-grasp-demo#4]
@giuliavezzani commented on [Thu Nov 09 2017](https://github.com/robotology/superquadric-grasp/issues/6)

It should be much nicer to pick the object up and put it in a basket on the left or on the right of the robot (according to which hand is used).

**Comment by pattacini** [comment]
@giuliavezzani this improvement is more concerned with this level of abstraction; that's why I moved the issue.

**Comment by giuliavezzani** [comment]
The code has been changed to make the robot clean the table. 
During the demo, two boxes should be located at the robot sides. According to which hand is used for grasping the object, the object will be moved to the right or the left box (So far, tha handover approach we have cannot be combined easily in this demo).
The code is to be tested on the robot.

**Comment by giuliavezzani** [comment]
The new code has been successfully tested on the robot.
